# Generated by Django 4.2.11 on 2024-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lahrech_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('day', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True)),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
